# Generated by Django 2.0.3 on 2018-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180411_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_examine',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
