# Generated by Django 2.0.3 on 2018-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comments_text', models.TextField(max_length=100)),
                ('ip_hash', models.CharField(max_length=13)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='comments',
            new_name='comments_quantity',
        ),
        migrations.AddField(
            model_name='article',
            name='comment_ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
