# Generated by Django 2.0.3 on 2018-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_examine_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=64)),
                ('cookie_name', models.CharField(default='!', max_length=64)),
                ('cookie_psaaword', models.CharField(default='!', max_length=64)),
                ('cookie_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
