# Generated by Django 2.0.3 on 2018-04-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180405_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_db',
        ),
    ]
