# Generated by Django 2.0.3 on 2018-04-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180412_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
