# Generated by Django 2.0.3 on 2018-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180405_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_ip',
            field=models.TextField(default='!'),
        ),
    ]
