# Generated by Django 2.0.3 on 2018-04-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_examine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_examine',
            old_name='name',
            new_name='user',
        ),
    ]
