# Generated by Django 2.0.3 on 2018-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180424_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
