# Generated by Django 2.0.3 on 2018-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='article_examine',
            name='title',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='article_examine',
            name='user',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='comment_db',
            name='comments_text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='name',
            field=models.CharField(max_length=11),
        ),
    ]
