# Generated by Django 2.0.3 on 2018-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180424_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_db',
            name='comments_text',
            field=models.TextField(max_length=450),
        ),
    ]
