# Generated by Django 2.0.3 on 2018-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180424_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(default=1, max_length=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='article_examine',
            name='title',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='article_examine',
            name='user',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='comment_db',
            name='comments_text',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='name',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
