# Generated by Django 2.0.3 on 2018-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180426_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_examine',
            name='label',
            field=models.CharField(default='!', max_length=110),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(default='!', max_length=110),
        ),
    ]
